tag_consensus:
  ros__parameters:
    max_estimate_age_ms: 2000
    max_reprojection_error: 0.3
    max_range: 5.0
    update_interval_ms: 10
    consensus_frame_id: "visual_pose_estimate"

oak:
  ros__parameters:
    driver:
      i_publish_tf_from_calibration: true
      i_tf_base_frame: intake_camera
      i_tf_parent_frame: ""
    pipeline_gen:
      i_nn_type: none
      i_pipeline_type: RGBD
      i_enable_imu: true
      i_enable_rgbd: true
      i_enable_diagnostics: true
    rgb:
      i_width: 512
      i_height: 512
    stereo:
      i_aligned: true
      i_width: 512
      i_height: 512

/intake_camera:
  usb_cam:
    ros__parameters:
      framerate: 30.0
      frame_id: "intake_camera"
      camera_name: "v1_intake_camera"
      pixel_format: "mjpeg2rgb"
      image_width: 1280
      image_height: 800
      camera_info_url: "package://kc_vision/config/camera_calibrations/v1_intake_camera.yaml"

  fuel_detector:
    ros__parameters:
      show_debug_displays: false
      occupancy_threshold: 0.5
      low:
        h: 0
        s: 96
        v: 115
      high:
        h: 88
        s: 255
        v: 255
      grid:
        frame_id: "intake_grid"
        cols: 20
        rows: 40
        cell_size: 0.03429

  resize:
    ros__parameters:
      use_scale: false
      width: 320.0
      height: 240.0